import { Lib } from "@/assets";
import { AdminDashboard, Logo } from "@/components";
import { useAuth } from "@/hooks";
import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";

const Home: NextPage = () => {
  /**
   * page states
   */
  const { user } = useAuth();

  return (
    <>
      <Head>
        <title>lms - Dashboard</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex h-full overflow-y-scroll rounded-[2rem] border scrollbar-hide">
        {user?.role === "admin" && <AdminDashboard />}

        {user?.role === "user" && (
          <div className="flex w-full flex-col items-center justify-center p-4">
            <Logo logoStyles="text-[3rem]" dotStyles="w-2 h-2 bg-primary" />

            <p className="mt-3 w-fit rounded-full bg-indigo-200/10 p-4  px-3 py-1 text-center text-xs capitalize leading-loose text-secondary shadow-sm xs:text-sm">
              Welcome to LMS.We provide you with upto date books and an easy and
              fast way to access them.
            </p>

            <p className="mt-10">
              Just Browse through, <br /> Click{" "}
              <span className="rounded-full bg-primary py-1 px-2 text-white">
                BORROW
              </span>{" "}
              and thats it, we will take care of the rest.
            </p>
          </div>
        )}

        {user?.role === undefined && (
          <div className="flex w-full flex-col gap-[5rem]">
            <div className="mt-10 flex flex-col items-center ">
              <Logo logoStyles="text-[3rem]" dotStyles="w-2 h-2 bg-primary" />

              <div className="text-c_yellow text-lg">
                Lets All Learn With Fast Access.
              </div>
            </div>

            <div className="flex">
              <div className="flex flex-col items-center justify-center">
                <p className="w-fit rounded-full  bg-indigo-200/10 px-3 py-1 text-xs capitalize leading-loose text-indigo-500 shadow-sm xs:text-sm">
                  Please Login To Access The System.
                </p>

                <p className="mt-4 px-2 text-center">
                  If you don&apos;t have an account yet, Create one with just a
                  few clicks.
                </p>
              </div>

              <div className="flex justify-end pr-10">
                <div className="md:w-[20rem] xmd:w-[25rem]">
                  <Image src={Lib} alt="" className="" />
                </div>
              </div>
            </div>
          </div>
        )}
      </main>
    </>
  );
};

export default Home;
